"use client";
import { AlertTriangle,Dices,Loader2,RefreshCw,Save,ShieldCheck } from "lucide-react";
import { useState } from "react";
import { NumberBall } from "@/components/draw/number-ball";
import type { GeneratedCombination,GenerationMethod,GeneratorConstraints } from "@/features/generator/types";

type Result={method:GenerationMethod;seed:string;constraints:GeneratorConstraints;modelVersion:string;drawCount:number;executionMs:number;attempts:number;combinations:GeneratedCombination[]};
const parseNumbers=(value:string)=>value.split(/[\s,，]+/).filter(Boolean).map(Number);
export function GeneratorWorkbench(){const[method,setMethod]=useState<GenerationMethod>("uniform_random"),[count,setCount]=useState(5),[seed,setSeed]=useState("mark-six-2026"),[required,setRequired]=useState(""),[excluded,setExcluded]=useState(""),[oddCount,setOddCount]=useState(""),[lowCount,setLowCount]=useState(""),[minSum,setMinSum]=useState(""),[maxSum,setMaxSum]=useState(""),[allowConsecutive,setAllowConsecutive]=useState(true),[maxEnding,setMaxEnding]=useState(""),[excludePrevious,setExcludePrevious]=useState(false),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState<Set<number>>(new Set());
  function freshSeed(){setSeed(globalThis.crypto?.randomUUID?.()??String(Date.now()));}
  async function generate(){setBusy(true);setError(null);setSaved(new Set());try{const constraints={required:parseNumbers(required),excluded:parseNumbers(excluded),oddCount:oddCount===""?undefined:Number(oddCount),lowCount:lowCount===""?undefined:Number(lowCount),minSum:minSum===""?undefined:Number(minSum),maxSum:maxSum===""?undefined:Number(maxSum),allowConsecutive,maxSameEndingDigit:maxEnding===""?undefined:Number(maxEnding),excludePreviousDraw:excludePrevious};const response=await fetch("/api/generator",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({method,count,seed,constraints})});const payload=await response.json() as {data?:Result;error?:{message:string;details?:unknown}};if(!response.ok||!payload.data)throw new Error(payload.error?.message??"產生失敗");setResult(payload.data);}catch(caught){setError(caught instanceof Error?caught.message:"產生失敗");setResult(null);}finally{setBusy(false);}}
  async function save(index:number){if(!result)return;setError(null);const combination=result.combinations[index];const response=await fetch("/api/generator/save",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({numbers:combination.numbers,method:result.method,seed:result.seed,constraints:result.constraints,historicalScore:combination.historicalScore})});const payload=await response.json() as {error?:{message:string}};if(response.status===401){setError("請先登入管理員／使用者帳戶，才可儲存組合。");return;}if(!response.ok){setError(payload.error?.message??"無法儲存組合");return;}setSaved((current)=>new Set(current).add(index));}
  return <div className="mt-9"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="方法"><select value={method} onChange={(event)=>setMethod(event.target.value as GenerationMethod)} className="input"><option value="uniform_random">Uniform random</option><option value="conditional_random">Conditional random</option><option value="historical_weighted">Historical weighted</option></select></Field><Field label="組數（1–50）"><input className="input" type="number" min="1" max="50" value={count} onChange={(event)=>setCount(Number(event.target.value))}/></Field><Field label="Random seed"><div className="flex gap-2"><input className="input" value={seed} onChange={(event)=>setSeed(event.target.value)}/><button type="button" onClick={freshSeed} aria-label="產生新 seed" className="grid size-11 shrink-0 place-items-center rounded-xl border border-white/12"><RefreshCw className="size-4"/></button></div></Field><Field label="固定號碼（逗號分隔）"><input className="input" value={required} onChange={(event)=>setRequired(event.target.value)} placeholder="例如 3, 8"/></Field><Field label="排除號碼"><input className="input" value={excluded} onChange={(event)=>setExcluded(event.target.value)} placeholder="例如 1, 49"/></Field><Field label="奇數數量"><OptionalSelect value={oddCount} setValue={setOddCount}/></Field><Field label="低號數量（1–24）"><OptionalSelect value={lowCount} setValue={setLowCount}/></Field><Field label="同尾數最多"><OptionalSelect value={maxEnding} setValue={setMaxEnding} minimum={1}/></Field><Field label="最小和值"><input className="input" type="number" min="21" max="279" value={minSum} onChange={(event)=>setMinSum(event.target.value)} placeholder="不限"/></Field><Field label="最大和值"><input className="input" type="number" min="21" max="279" value={maxSum} onChange={(event)=>setMaxSum(event.target.value)} placeholder="不限"/></Field><label className="flex min-h-11 items-center gap-3 pt-6"><input type="checkbox" checked={allowConsecutive} onChange={(event)=>setAllowConsecutive(event.target.checked)} className="size-4 accent-indigo-500"/>允許連號</label><label className="flex min-h-11 items-center gap-3 pt-6"><input type="checkbox" checked={excludePrevious} onChange={(event)=>setExcludePrevious(event.target.checked)} className="size-4 accent-indigo-500"/>排除上一期主號碼</label></div><button type="button" disabled={busy} onClick={()=>void generate()} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-500 px-5 font-bold shadow-lg shadow-indigo-500/20 hover:bg-indigo-400 disabled:opacity-60">{busy?<Loader2 className="size-5 animate-spin"/>:<Dices className="size-5"/>}{busy?"產生中…":"產生組合"}</button></section>
    {error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/20 bg-red-400/8 p-4 text-sm text-red-200"><AlertTriangle className="mr-2 inline size-4"/>{error}</p>}
    {result&&<section className="mt-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">產生結果</h2><p className="mt-1 text-sm text-slate-400">{result.modelVersion} · seed: <code>{result.seed}</code> · verified 樣本 {result.drawCount.toLocaleString("zh-HK")} 期 · {result.executionMs}ms</p></div><span className="flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/8 px-3 py-2 text-xs text-emerald-200"><ShieldCheck className="size-4"/>可用相同 seed 重現</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{result.combinations.map((combination,index)=><article key={combination.numbers.join("-")} className="rounded-2xl border border-white/10 bg-[#141b2d]/80 p-5"><div className="flex items-center justify-between"><p className="font-bold">組合 {index+1}</p><button type="button" disabled={saved.has(index)} onClick={()=>void save(index)} className="flex min-h-10 items-center gap-2 rounded-xl border border-white/12 px-3 text-sm font-semibold disabled:text-emerald-300"><Save className="size-4"/>{saved.has(index)?"已儲存":"儲存"}</button></div><div className="mt-4 flex flex-wrap gap-2">{combination.numbers.map((number)=><NumberBall key={number} number={number}/>)}</div>{combination.historicalScore!==null&&<p className="mt-4 text-xs text-slate-400">歷史權重分數：{combination.historicalScore.toFixed(1)}（不是中獎機率）</p>}<ul className="mt-4 list-disc space-y-1 pl-5 text-xs leading-5 text-slate-400">{combination.explanation.map((line)=><li key={line}>{line}</li>)}</ul></article>)}</div></section>}
    <style jsx global>{`.input{min-height:44px;width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.12);background:rgba(2,6,23,.6);padding:0 12px;outline:none}.input:focus{border-color:#818cf8}`}</style></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-2 block text-sm text-slate-400">{label}</span>{children}</label>;}
function OptionalSelect({value,setValue,minimum=0}:{value:string;setValue:(value:string)=>void;minimum?:number}){return <select className="input" value={value} onChange={(event)=>setValue(event.target.value)}><option value="">不限</option>{Array.from({length:7-minimum},(_,index)=>index+minimum).map((number)=><option key={number} value={number}>{number}</option>)}</select>;}
