import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, ChevronRight, Dices, Info, Sparkles, TrendingUp } from "lucide-react";
import Link from "next/link";
import { NumberBall } from "@/components/draw/number-ball";

const demoNumbers = [3, 8, 19, 24, 37, 45];
const stats = [{ label: "已收錄期數", value: "2,418", note: "DEMO 資料", icon: CalendarDays }, { label: "分析號碼", value: "49", note: "正選與特別號", icon: BarChart3 }, { label: "理論組合", value: "13.98M", note: "C(49, 6)", icon: TrendingUp }];

export function Dashboard() {
  return <div className="mx-auto max-w-360 px-5 py-10 lg:px-8 lg:py-14">
    <section className="grid items-end gap-10 lg:grid-cols-[1.15fr_.85fr]">
      <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-400/25 bg-indigo-400/8 px-3 py-2 text-xs font-medium text-indigo-200"><Sparkles className="size-3.5" />以數據理解隨機，而非預測未來</div><h1 className="max-w-3xl text-4xl font-bold leading-[1.12] tracking-tight sm:text-5xl lg:text-6xl">看清每一個號碼背後的<br/><span className="bg-gradient-to-r from-indigo-300 to-emerald-300 bg-clip-text text-transparent">歷史脈絡與機率</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">查閱歷史結果、探索號碼型態，並以可重現的方式比較組合方法與純隨機基準。</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/zh-HK/analytics" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-indigo-500 px-5 font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400">探索數據 <ArrowRight className="size-4" /></Link><Link href="/zh-HK/methodology" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/12 bg-white/5 px-5 font-semibold text-slate-200 hover:bg-white/8"><Info className="size-4" />了解方法</Link></div></div>
      <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-[#141b2d]/90 p-6 shadow-2xl shadow-black/25"><div className="absolute right-0 top-0 rounded-bl-2xl bg-amber-400 px-3 py-1.5 text-[10px] font-black tracking-wider text-slate-950">DEMO DATA</div><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">最新示範結果</p><p className="mt-2 text-xl font-bold">第 26/085 期</p></div><span className="text-sm text-slate-400">2026.07.18</span></div><div className="mt-8 flex flex-wrap gap-2.5">{demoNumbers.map((n) => <NumberBall key={n} number={n} />)}<span className="mx-1 self-center text-slate-600">+</span><NumberBall number={12} extra /></div><div className="mt-7 flex items-center justify-between border-t border-white/8 pt-5 text-sm"><span className="text-slate-400">所有展示數據均為示範</span><Link href="/zh-HK/results" className="flex items-center gap-1 font-semibold text-indigo-300">查看結果 <ChevronRight className="size-4" /></Link></div></div>
    </section>
    <section aria-label="數據摘要" className="mt-14 grid gap-4 sm:grid-cols-3">{stats.map(({ label, value, note, icon: Icon }) => <article key={label} className="rounded-2xl border border-white/8 bg-white/[.035] p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-indigo-400/10 text-indigo-300"><Icon className="size-5" /></span></div><p className="mt-3 text-xs text-slate-500">{note}</p></article>)}</section>
    <section className="mt-12 grid gap-5 lg:grid-cols-3"><Feature href="/zh-HK/analytics" icon={BarChart3} title="號碼與型態分析" text="用清晰圖表查看頻率、間距、奇偶、大小、總和與號碼配對。" label="開啟數據分析"/><Feature href="/zh-HK/generator" icon={Dices} title="可重現組合實驗" text="以固定 seed 建立純隨機或條件式組合，每次結果都可以重現。" label="開始組合實驗"/><Feature href="/zh-HK/checker" icon={CheckCircle2} title="快速對獎" text="手動輸入六個號碼，核對指定期數與正選、特別號命中結果。" label="前往對獎"/></section>
    <section className="mt-12 rounded-2xl border border-amber-300/15 bg-amber-300/[.055] p-5 text-sm leading-7 text-amber-100/80"><div className="flex gap-3"><Info className="mt-1 size-5 shrink-0 text-amber-300"/><p><strong className="text-amber-200">重要機率說明：</strong>所有六個號碼組合在公平及獨立攪珠下，中頭獎的理論機率相同。歷史頻率、冷熱號碼、模型評分及回測結果不代表未來結果。</p></div></section>
  </div>;
}

function Feature({ href, icon: Icon, title, text, label }: { href: string; icon: typeof BarChart3; title: string; text: string; label: string }) { return <article className="group rounded-2xl border border-white/8 bg-[#141b2d]/70 p-6 transition hover:-translate-y-1 hover:border-indigo-400/25"><span className="grid size-12 place-items-center rounded-2xl bg-indigo-500/10 text-indigo-300"><Icon className="size-6"/></span><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="mt-3 min-h-14 text-sm leading-7 text-slate-400">{text}</p><Link href={href} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-indigo-300">{label}<ChevronRight className="size-4 transition group-hover:translate-x-1"/></Link></article>; }
