import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, ChevronRight, Clock3, Dices, FlaskConical, Info, RefreshCw, SearchCheck, TrendingUp } from "lucide-react";
import Link from "next/link";
import { NumberBall } from "@/components/draw/number-ball";
import { ShareResultButton } from "@/components/home/share-result-button";
import { formatDrawDate } from "@/components/draw/draw-card";
import type { DrawSummary } from "@/features/draws/types";

export function LiveDashboard({latest,recent,total,locale}:{latest:DrawSummary|null;recent:DrawSummary[];total:number;locale:string}){
 const prefix=`/${locale}`,displayed=recent.slice(0,10),counts=Array.from({length:50},()=>0);displayed.forEach(draw=>draw.mainNumbers.forEach(number=>counts[number]++));
 const overdue=Array.from({length:49},(_,index)=>({number:index+1,gap:recent.findIndex(draw=>draw.mainNumbers.includes(index+1))})).map(item=>({...item,gap:item.gap<0?recent.length:item.gap})).sort((a,b)=>b.gap-a.gap||a.number-b.number).slice(0,5);
 const bands=[[1,9],[10,19],[20,29],[30,39],[40,49]] as const;
 const hot=Array.from({length:49},(_,index)=>({number:index+1,count:counts[index+1]})).sort((a,b)=>b.count-a.count||a.number-b.number).slice(0,5),maximum=Math.max(...hot.map(item=>item.count),1);
 const updated=latest?.sourceRetrievedAt?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Hong_Kong"}).format(new Date(latest.sourceRetrievedAt)):latest?formatDrawDate(latest.drawDate,locale):"—";
 return <div className="mx-auto max-w-360 px-4 py-6 sm:px-5 lg:px-8 lg:py-8">
  <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-300">首頁 / 儀表板</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">六合彩數據儀表板</h1></div><div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-4 py-2 text-xs text-slate-400"><RefreshCw className="size-3.5 text-emerald-300"/>資料更新：{updated}</div></div>
  <section className="grid gap-4 xl:grid-cols-[1.45fr_.75fr]">
   <article className="relative overflow-hidden rounded-2xl border border-emerald-400/20 bg-[#121a2b] p-5 sm:p-6"><div className="absolute right-0 top-0 rounded-bl-xl bg-emerald-400 px-3 py-1.5 text-[10px] font-black text-slate-950">VERIFIED</div>{latest?<><div className="flex flex-wrap items-start justify-between gap-3 pr-16"><div><p className="text-sm text-slate-400">最新開獎結果</p><h2 className="mt-1 text-2xl font-bold">{latest.drawNumber}</h2></div><time dateTime={latest.drawDate} className="text-sm text-slate-400">{formatDrawDate(latest.drawDate,locale)}</time></div><div className="mt-7 flex flex-wrap items-center gap-2 sm:gap-3">{latest.mainNumbers.map(number=><NumberBall key={number} number={number}/>)}<span className="px-1 text-xl text-slate-500">+</span><NumberBall number={latest.extraNumber} extra/></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-white/8 pt-4"><span className="text-xs text-slate-500">來源：{latest.sourceName??"已核實資料"}</span><div className="flex gap-2"><ShareResultButton drawNumber={latest.drawNumber} drawDate={formatDrawDate(latest.drawDate,locale)} numbers={latest.mainNumbers} extra={latest.extraNumber}/><Link href={`${prefix}/results`} className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-indigo-400/30 px-3 text-sm font-semibold text-indigo-300">查看詳情 <ChevronRight className="size-4"/></Link></div></div></>:<p className="py-12 text-slate-400">目前沒有已核實開獎資料。</p>}</article>
   <article className="rounded-2xl border border-indigo-400/20 bg-gradient-to-br from-indigo-500/15 to-[#121a2b] p-5 sm:p-6"><div className="flex items-center gap-2 text-indigo-300"><Clock3 className="size-5"/><h2 className="font-bold">資料狀態</h2></div><p className="mt-6 text-3xl font-bold tabular-nums">{total.toLocaleString(locale)}</p><p className="mt-1 text-sm text-slate-400">已核實歷史期數</p><div className="mt-6 space-y-3 text-sm"><Status label="資料庫" value="正常"/><Status label="最新期數" value={latest?.drawNumber??"—"}/><Status label="來源" value={latest?.sourceName??"—"}/></div></article>
  </section>
  <section aria-label="資料摘要" className="mt-4 grid gap-3 sm:grid-cols-3"><Stat icon={CalendarDays} label="已核實開獎" value={total.toLocaleString(locale)} note="verified dataset"/><Stat icon={BarChart3} label="可選號碼" value="49" note="每期 6+1 個號碼"/><Stat icon={TrendingUp} label="頭獎理論組合" value="13.98M" note="C(49, 6)"/></section>
  <section className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]">
   <article className="rounded-2xl border border-white/8 bg-[#121a2b] p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">熱門號碼 Top 5</h2><p className="mt-1 text-xs text-slate-500">最近 {displayed.length} 期正選號碼</p></div><Link href={`${prefix}/analytics?window=10`} className="text-xs font-semibold text-indigo-300">完整分析</Link></div><div className="mt-6 space-y-4">{hot.map(item=><div key={item.number} className="grid grid-cols-[2.5rem_1fr_2rem] items-center gap-3"><span className="font-mono font-bold text-slate-200">{String(item.number).padStart(2,"0")}</span><div className="h-2 overflow-hidden rounded-full bg-white/6"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-emerald-400" style={{width:`${item.count/maximum*100}%`}}/></div><span className="text-right text-sm tabular-nums text-slate-400">{item.count}</span></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-600">只描述近期出現次數，不代表未來中獎機率。</p></article>
   <article className="overflow-hidden rounded-2xl border border-white/8 bg-[#121a2b]"><div className="flex items-center justify-between p-5"><div><h2 className="font-bold">最近 10 期結果</h2><p className="mt-1 text-xs text-slate-500">全部來自 verified dataset</p></div><Link href={`${prefix}/results`} className="text-xs font-semibold text-indigo-300">更多</Link></div><div className="overflow-x-auto"><table className="w-full min-w-170 text-left text-sm"><thead className="border-y border-white/8 bg-white/[.025] text-xs text-slate-500"><tr><th className="px-5 py-3">期數</th><th className="px-4 py-3">日期</th><th className="px-4 py-3">正選號碼</th><th className="px-4 py-3">特別號</th></tr></thead><tbody>{displayed.map(draw=><tr key={draw.drawNumber} className="border-b border-white/6 last:border-0"><td className="px-5 py-3 font-semibold">{draw.drawNumber}</td><td className="whitespace-nowrap px-4 py-3 text-slate-400">{formatDrawDate(draw.drawDate,locale)}</td><td className="px-4 py-3 font-mono tabular-nums text-slate-300">{draw.mainNumbers.map(number=>String(number).padStart(2,"0")).join(" · ")}</td><td className="px-4 py-3 font-mono font-bold text-amber-300">{String(draw.extraNumber).padStart(2,"0")}</td></tr>)}</tbody></table></div></article>
  </section>
  <section className="mt-4 grid gap-4 xl:grid-cols-[.72fr_1.28fr]">
   <article className="rounded-2xl border border-white/8 bg-[#121a2b] p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">最長未出現號碼</h2><p className="mt-1 text-xs text-slate-500">按最近最多 100 期正選號碼計算</p></div><Link href={`${prefix}/analytics`} className="text-xs font-semibold text-indigo-300">查看分析</Link></div><div className="mt-5 space-y-3">{overdue.map((item,index)=><div key={item.number} className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full border border-white/10 bg-white/[.04] font-mono text-sm font-bold">{String(item.number).padStart(2,"0")}</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-white/6"><div className="h-full rounded-full bg-gradient-to-r from-amber-500 to-rose-400" style={{width:`${100-index*12}%`}}/></div><span className="w-14 text-right text-xs tabular-nums text-slate-400">{item.gap} 期</span></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-600">間隔較長不表示下一期較容易出現。</p></article>
   <article className="rounded-2xl border border-white/8 bg-[#121a2b] p-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="font-bold">最近 10 期號碼區間熱度</h2><p className="mt-1 text-xs text-slate-500">每格代表該期落在指定區間的正選號碼數量</p></div><div className="flex items-center gap-2 text-[10px] text-slate-500"><span>少</span><span className="size-3 rounded-sm bg-indigo-950"/><span className="size-3 rounded-sm bg-indigo-600"/><span className="size-3 rounded-sm bg-emerald-400"/><span>多</span></div></div><div className="mt-5 overflow-x-auto"><div className="min-w-150"><div className="grid grid-cols-[4rem_repeat(10,1fr)] gap-1 text-center text-[10px] text-slate-600"><span/>{displayed.map(draw=><span key={draw.drawNumber} className="truncate">{draw.drawNumber.replace(/^[^/]*\//,"")}</span>)}</div>{bands.map(([from,to])=><div key={from} className="mt-1 grid grid-cols-[4rem_repeat(10,1fr)] gap-1"><span className="self-center text-xs text-slate-500">{from}–{to}</span>{displayed.map(draw=>{const value=draw.mainNumbers.filter(number=>number>=from&&number<=to).length;return <span key={draw.drawNumber} title={`${draw.drawNumber}：${value} 個`} aria-label={`${from}至${to}，${draw.drawNumber}，${value}個`} className={`h-8 rounded-md ${value===0?"bg-white/[.035]":value===1?"bg-indigo-900":value===2?"bg-indigo-600":value===3?"bg-emerald-500":"bg-amber-400"}`}/>})}</div>)}</div></div></article>
  </section>  <section className="mt-4"><h2 className="mb-3 font-bold">快速功能</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Quick href={`${prefix}/generator`} icon={Dices} title="組合產生器" text="建立可重現組合"/><Quick href={`${prefix}/analytics`} icon={BarChart3} title="號碼分析" text="頻率、間隔與型態"/><Quick href={`${prefix}/checker`} icon={SearchCheck} title="對獎工具" text="核對已核實結果"/><Quick href={`${prefix}/backtest`} icon={FlaskConical} title="模型回測" text="比較方法與隨機基準"/></div></section>
  <section className="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-sm leading-6 text-amber-100/75"><Info className="mr-2 inline size-4 text-amber-300"/><strong>重要聲明：</strong>歷史頻率不能預測未來結果，所有組合的頭獎理論機率相同。</section>
 </div>;
}
function Status({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3 border-t border-white/8 pt-3"><span className="text-slate-500">{label}</span><span className="max-w-36 truncate font-medium text-emerald-300">{value}</span></div>}
function Stat({icon:Icon,label,value,note}:{icon:typeof CalendarDays;label:string;value:string;note:string}){return <article className="flex items-center gap-4 rounded-2xl border border-white/8 bg-white/[.03] p-4"><span className="grid size-10 place-items-center rounded-xl bg-indigo-500/10 text-indigo-300"><Icon className="size-5"/></span><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold tabular-nums">{value}</p><p className="text-[10px] text-slate-600">{note}</p></div></article>}
function Quick({href,icon:Icon,title,text}:{href:string;icon:typeof CheckCircle2;title:string;text:string}){return <Link href={href} className="group flex min-h-24 items-center gap-4 rounded-2xl border border-white/8 bg-[#121a2b] p-4 transition hover:-translate-y-0.5 hover:border-indigo-400/30"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-indigo-500/10 text-indigo-300"><Icon className="size-5"/></span><span><strong className="block text-sm">{title}</strong><span className="mt-1 block text-xs text-slate-500">{text}</span></span><ArrowRight className="ml-auto size-4 text-slate-600 transition group-hover:translate-x-1"/></Link>}