import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, ChevronRight, Dices, Info, Sparkles, TrendingUp } from "lucide-react";
import Link from "next/link";
import { NumberBall } from "@/components/draw/number-ball";
import { formatDrawDate } from "@/components/draw/draw-card";
import type { DrawSummary } from "@/features/draws/types";

export function LiveDashboard({ latest, total, locale }: { latest: DrawSummary | null; total: number; locale: string }) {
  const prefix = `/${locale}`;
  return <div className="mx-auto max-w-360 px-5 py-10 lg:px-8 lg:py-14">
    <section className="grid items-end gap-10 lg:grid-cols-[1.15fr_.85fr]">
      <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/25 bg-emerald-400/8 px-3 py-2 text-xs font-medium text-emerald-200"><Sparkles className="size-3.5"/>已連接 verified 即時資料</div><h1 className="max-w-3xl text-4xl font-bold leading-[1.12] tracking-tight sm:text-5xl lg:text-6xl">用數據理解六合彩<br/><span className="bg-gradient-to-r from-indigo-300 to-emerald-300 bg-clip-text text-transparent">而不是預測未來</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">探索歷史開獎、號碼分布與可重現的統計分析。所有公開結果只使用已核實資料。</p><div className="mt-7 flex flex-wrap gap-3"><Link href={`${prefix}/results`} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-indigo-500 px-5 font-semibold text-white shadow-lg shadow-indigo-500/20 hover:bg-indigo-400">查看開獎結果 <ArrowRight className="size-4"/></Link><Link href={`${prefix}/methodology`} className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/12 bg-white/5 px-5 font-semibold text-slate-200"><Info className="size-4"/>了解方法</Link></div></div>
      <div className="relative overflow-hidden rounded-3xl border border-emerald-400/20 bg-[#141b2d]/90 p-6 shadow-2xl shadow-black/25"><div className="absolute right-0 top-0 rounded-bl-2xl bg-emerald-400 px-3 py-1.5 text-[10px] font-black tracking-wider text-slate-950">VERIFIED DATA</div>{latest ? <><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">最新開獎結果</p><p className="mt-2 text-xl font-bold">{latest.drawNumber}</p></div><time dateTime={latest.drawDate} className="text-sm text-slate-400">{formatDrawDate(latest.drawDate, locale)}</time></div><div className="mt-8 flex flex-wrap gap-2.5">{latest.mainNumbers.map((number) => <NumberBall key={number} number={number}/>)}<span className="mx-1 self-center text-slate-600">+</span><NumberBall number={latest.extraNumber} extra/></div></> : <p className="py-12 text-slate-400">目前沒有已核實開獎資料。</p>}<div className="mt-7 flex items-center justify-between border-t border-white/8 pt-5 text-sm"><span className="text-slate-400">來源：{latest?.sourceName ?? "—"}</span><Link href={`${prefix}/results`} className="flex items-center gap-1 font-semibold text-indigo-300">全部結果 <ChevronRight className="size-4"/></Link></div></div>
    </section>
    <section aria-label="資料摘要" className="mt-14 grid gap-4 sm:grid-cols-3"><Stat label="已核實開獎" value={total.toLocaleString("zh-HK")} note="Supabase verified dataset" icon={CalendarDays}/><Stat label="可選號碼" value="49" note="每期六個主號碼及一個特別號碼" icon={BarChart3}/><Stat label="頭獎組合" value="13.98M" note="C(49, 6)" icon={TrendingUp}/></section>
    <section className="mt-12 grid gap-5 lg:grid-cols-3"><Feature href={`${prefix}/analytics`} icon={BarChart3} title="統計分析" text="以已核實歷史資料計算號碼頻率、間隔與組合特徵。"/><Feature href={`${prefix}/generator`} icon={Dices} title="組合產生器" text="使用可重現的隨機種子產生組合，不作中獎保證。"/><Feature href={`${prefix}/checker`} icon={CheckCircle2} title="結果核對" text="把選號與已核實開獎結果比較。"/></section>
    <section className="mt-12 rounded-2xl border border-amber-300/15 bg-amber-300/[.055] p-5 text-sm leading-7 text-amber-100/80"><div className="flex gap-3"><Info className="mt-1 size-5 shrink-0 text-amber-300"/><p><strong className="text-amber-200">重要聲明：</strong>歷史統計不能提高每個獨立隨機組合的中獎機率。本網站只供數據研究及教育用途，並非投注建議。</p></div></section>
  </div>;
}
function Stat({ label,value,note,icon:Icon }: { label:string; value:string; note:string; icon:typeof CalendarDays }) { return <article className="rounded-2xl border border-white/8 bg-white/[.035] p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-indigo-400/10 text-indigo-300"><Icon className="size-5"/></span></div><p className="mt-3 text-xs text-slate-500">{note}</p></article>; }
function Feature({ href,icon:Icon,title,text }: { href:string; icon:typeof BarChart3; title:string; text:string }) { return <article className="rounded-2xl border border-white/8 bg-[#141b2d]/70 p-6"><span className="grid size-12 place-items-center rounded-2xl bg-indigo-500/10 text-indigo-300"><Icon className="size-6"/></span><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="mt-3 min-h-14 text-sm leading-7 text-slate-400">{text}</p><Link href={href} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-indigo-300">前往 <ChevronRight className="size-4"/></Link></article>; }
