import { Activity, BarChart3, Clock3, Grid3X3, Info, Sigma } from "lucide-react";
import type { NumberStatistic, PairStatistic, PatternStatistics } from "@/features/analytics/types";
import { NumberBall } from "@/components/draw/number-ball";

type Filters={window:"all"|"10"|"30"|"50"|"100"|"custom";from?:string;to?:string;includeExtra:boolean};
export function AnalyticsDashboard({numbers,patterns,pairs,filters,locale}:{numbers:NumberStatistic[];patterns:PatternStatistics;pairs:PairStatistic[];filters:Filters;locale:string}){
  const base=`/${locale}/analytics`,maxFrequency=Math.max(1,...numbers.map((item)=>item.frequency)),top=[...numbers].sort((a,b)=>b.frequency-a.frequency||a.number-b.number).slice(0,6),overdue=[...numbers].sort((a,b)=>(b.drawsSinceLastSeen??-1)-(a.drawsSinceLastSeen??-1)).slice(0,6);
  return <div className="mx-auto max-w-360 px-5 py-12 lg:px-8"><header className="max-w-3xl"><span className="mb-5 grid size-12 place-items-center rounded-2xl bg-indigo-500/12 text-indigo-300"><BarChart3 className="size-6"/></span><p className="text-xs font-bold uppercase tracking-[.2em] text-indigo-300">Verified analytics</p><h1 className="mt-3 text-3xl font-bold sm:text-5xl">歷史數據分析</h1><p className="mt-5 text-lg leading-8 text-slate-400">以下統計只描述已核實的歷史開獎，不代表任何號碼在未來較容易出現。</p></header>
    <form action={base} className="mt-9 grid gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-5 md:grid-cols-5"><label><span className="mb-2 block text-sm text-slate-400">統計範圍</span><select name="window" defaultValue={filters.window} className="min-h-11 w-full rounded-xl border border-white/12 bg-slate-950/80 px-3"><option value="all">全部期數</option><option value="10">最近 10 期</option><option value="30">最近 30 期</option><option value="50">最近 50 期</option><option value="100">最近 100 期</option><option value="custom">自訂日期</option></select></label><label><span className="mb-2 block text-sm text-slate-400">由</span><input type="date" name="from" defaultValue={filters.from} className="min-h-11 w-full rounded-xl border border-white/12 bg-slate-950/40 px-3"/></label><label><span className="mb-2 block text-sm text-slate-400">至</span><input type="date" name="to" defaultValue={filters.to} className="min-h-11 w-full rounded-xl border border-white/12 bg-slate-950/40 px-3"/></label><label className="flex min-h-11 items-end gap-2 pb-3"><input type="checkbox" name="includeExtra" value="true" defaultChecked={filters.includeExtra} className="size-4 accent-indigo-500"/><span className="text-sm">包括特別號碼</span></label><div className="flex items-end"><button className="min-h-11 w-full rounded-xl bg-indigo-500 px-4 font-semibold hover:bg-indigo-400">更新分析</button></div></form>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Activity} label="樣本期數" value={patterns.drawCount.toLocaleString("zh-HK")}/><Metric icon={Sigma} label="平均和值" value={patterns.averageSum.toFixed(1)}/><Metric icon={Grid3X3} label="和值範圍" value={`${patterns.minimumSum}–${patterns.maximumSum}`}/><Metric icon={Clock3} label="有連號期數" value={`${(patterns.consecutiveRate*100).toFixed(1)}%`}/></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><Highlight title="歷史出現最多" items={top} mode="frequency"/><Highlight title="距上次出現最久" items={overdue} mode="since"/></section>
    <section className="mt-8 rounded-2xl border border-white/10 bg-[#141b2d]/75 p-5"><div><h2 className="text-xl font-bold">1–49 號碼統計</h2><p className="mt-2 text-sm text-slate-400">偏差 = 實際次數相對於理論平均次數的差異，只屬描述性指標。</p></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-190 text-left text-sm"><thead className="text-slate-400"><tr><th className="p-3">號碼</th><th>出現次數</th><th className="w-64">相對頻率</th><th>理論平均</th><th>偏差</th><th>距今期數</th><th>平均間隔</th></tr></thead><tbody>{numbers.map((item)=><tr key={item.number} className="border-t border-white/8"><td className="p-3"><span className="inline-grid size-9 place-items-center rounded-full bg-indigo-500 font-mono font-bold">{item.number}</span></td><td className="font-semibold tabular-nums">{item.frequency}</td><td><div className="h-2 rounded-full bg-white/8"><div className="h-2 rounded-full bg-gradient-to-r from-indigo-500 to-emerald-400" style={{width:`${item.frequency/maxFrequency*100}%`}}/></div></td><td>{item.expectedFrequency.toFixed(1)}</td><td className={item.deviationFromExpected>=0?"text-emerald-300":"text-amber-300"}>{item.deviationFromExpected>=0?"+":""}{(item.deviationFromExpected*100).toFixed(1)}%</td><td>{item.drawsSinceLastSeen??"—"}</td><td>{item.averageGap?.toFixed(1)??"—"}</td></tr>)}</tbody></table></div></section>
    <section className="mt-8 grid gap-5 xl:grid-cols-2"><PatternTable title="奇偶分布" rows={patterns.oddEven.map((x)=>({label:`${x.odd} 奇 / ${x.even} 偶`,count:x.count}))} total={patterns.drawCount}/><PatternTable title="低高分布（1–24 / 25–49）" rows={patterns.lowHigh.map((x)=>({label:`${x.low} 低 / ${x.high} 高`,count:x.count}))} total={patterns.drawCount}/></section>
    <section className="mt-8 rounded-2xl border border-white/10 bg-[#141b2d]/75 p-5"><h2 className="text-xl font-bold">常見號碼 Pair</h2><p className="mt-2 text-sm text-slate-400">每期六個主號碼內的兩兩共同出現次數。</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{pairs.slice(0,20).map((pair,index)=><article key={pair.numbers.join("-")} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.03] p-3"><div className="flex gap-2"><NumberBall number={pair.numbers[0]}/><NumberBall number={pair.numbers[1]}/></div><div className="text-right"><p className="font-bold">#{index+1}</p><p className="text-xs text-slate-400">{pair.count} 次 · {(pair.rate*100).toFixed(1)}%</p></div></article>)}</div></section>
    <aside className="mt-8 flex gap-3 rounded-2xl border border-amber-300/15 bg-amber-300/[.055] p-5 text-sm leading-7 text-amber-100/80"><Info className="mt-1 size-5 shrink-0 text-amber-300"/><p>開獎被視為獨立隨機事件。「熱」、「冷」、「偏差」或「長時間未出現」不會改變下一期的理論機率。</p></aside>
  </div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Activity;label:string;value:string}){return <article className="rounded-2xl border border-white/8 bg-white/[.035] p-5"><span className="grid size-10 place-items-center rounded-xl bg-indigo-500/10 text-indigo-300"><Icon className="size-5"/></span><p className="mt-4 text-sm text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums">{value}</p></article>;}
function Highlight({title,items,mode}:{title:string;items:NumberStatistic[];mode:"frequency"|"since"}){return <section className="rounded-2xl border border-white/10 bg-[#141b2d]/75 p-5"><h2 className="font-bold">{title}</h2><div className="mt-4 flex flex-wrap gap-3">{items.map((item)=><div key={item.number} className="text-center"><NumberBall number={item.number}/><p className="mt-2 text-xs text-slate-400">{mode==="frequency"?`${item.frequency} 次`:`${item.drawsSinceLastSeen??"—"} 期`}</p></div>)}</div></section>;}
function PatternTable({title,rows,total}:{title:string;rows:Array<{label:string;count:number}>;total:number}){return <section className="rounded-2xl border border-white/10 bg-[#141b2d]/75 p-5"><h2 className="text-lg font-bold">{title}</h2><table className="mt-4 w-full text-sm"><thead className="text-left text-slate-400"><tr><th className="py-2">組合</th><th>期數</th><th>比例</th></tr></thead><tbody>{rows.map((row)=><tr key={row.label} className="border-t border-white/8"><td className="py-2">{row.label}</td><td>{row.count}</td><td>{total?(row.count/total*100).toFixed(1):"0.0"}%</td></tr>)}</tbody></table></section>;}
