import type{BacktestDraw,BacktestMetrics,BacktestResult}from"@/features/backtest/types";
import{classifyPrize}from"@/lib/checker/prize";
import{generateCombinations}from"@/lib/generator/engine";
import{calculateNumberFrequency}from"@/lib/statistics/draw-analytics";

type Accumulator={hits:number[];prizes:Array<number|null>;knownReturn:number;knownWinningPredictions:number;winningPredictions:number};
function emptyAccumulator():Accumulator{return{hits:[],prizes:[],knownReturn:0,knownWinningPredictions:0,winningPredictions:0};}
function evaluate(acc:Accumulator,numbers:number[],target:BacktestDraw){const mainSet=new Set(target.mainNumbers),mainHits=numbers.filter((number)=>mainSet.has(number)).length,extraHit=numbers.includes(target.extraNumber),division=classifyPrize(mainHits,extraHit);acc.hits.push(mainHits);acc.prizes.push(division);if(division!==null){acc.winningPredictions++;if(division===1&&target.firstPrizeDividend!==null){acc.knownWinningPredictions++;acc.knownReturn+=target.firstPrizeDividend;}}}
function metrics(acc:Accumulator,unitCost:number):BacktestMetrics{const hitDistribution=Object.fromEntries(Array.from({length:7},(_,hits)=>[String(hits),acc.hits.filter((value)=>value===hits).length])),prizeDistribution=Object.fromEntries(Array.from({length:7},(_,index)=>[String(index+1),acc.prizes.filter((value)=>value===index+1).length])),simulatedCost=acc.hits.length*unitCost;return{predictions:acc.hits.length,averageMainHits:acc.hits.length?acc.hits.reduce((a,b)=>a+b,0)/acc.hits.length:0,hitDistribution,prizeDistribution,knownReturn:acc.knownReturn,returnCoverage:acc.winningPredictions?acc.knownWinningPredictions/acc.winningPredictions:null,simulatedCost,knownRoi:simulatedCost?(acc.knownReturn-simulatedCost)/simulatedCost:0};}
export function runWalkForwardBacktest({draws,method,targetDrawCount,minimumTrainingDraws,combinationsPerDraw,baseSeed,seedCount,unitCost=10}:{draws:BacktestDraw[];method:"uniform_random"|"historical_weighted";targetDrawCount:number;minimumTrainingDraws:number;combinationsPerDraw:number;baseSeed:string;seedCount:number;unitCost?:number}):BacktestResult{
  const chronological=[...draws].sort((a,b)=>a.drawDate.localeCompare(b.drawDate));if(chronological.length<=minimumTrainingDraws)throw new Error("INSUFFICIENT_TRAINING_DATA");const available=chronological.length-minimumTrainingDraws,actualTargets=Math.min(targetDrawCount,available),start=chronological.length-actualTargets,strategyAcc=emptyAccumulator(),baselineAcc=emptyAccumulator(),targets:BacktestResult["targets"]=[],started=performance.now();
  for(let targetIndex=start;targetIndex<chronological.length;targetIndex++){const training=chronological.slice(0,targetIndex),target=chronological[targetIndex],frequencies=calculateNumberFrequency(training),strategyBefore=strategyAcc.hits.length,baselineBefore=baselineAcc.hits.length;for(let seedIndex=0;seedIndex<seedCount;seedIndex++){const seed=`${baseSeed}:${target.drawNumber}:${seedIndex}`,constraints={required:[],excluded:[],allowConsecutive:true,excludePreviousDraw:false};const strategy=generateCombinations({method,count:combinationsPerDraw,seed,constraints,frequencies}),baseline=generateCombinations({method:"uniform_random",count:combinationsPerDraw,seed:`baseline:${seed}`,constraints});for(const combination of strategy.combinations)evaluate(strategyAcc,combination.numbers,target);for(const combination of baseline.combinations)evaluate(baselineAcc,combination.numbers,target);}const strategySlice=strategyAcc.hits.slice(strategyBefore),baselineSlice=baselineAcc.hits.slice(baselineBefore);targets.push({drawNumber:target.drawNumber,drawDate:target.drawDate,trainingEndDate:training.at(-1)?.drawDate??"",trainingDrawCount:training.length,strategyAverageHits:strategySlice.reduce((a,b)=>a+b,0)/strategySlice.length,baselineAverageHits:baselineSlice.reduce((a,b)=>a+b,0)/baselineSlice.length});}
  const strategy=metrics(strategyAcc,unitCost),baseline=metrics(baselineAcc,unitCost);return{method,modelVersion:"backtest-v1",baseSeed,seedCount,targetDraws:actualTargets,minimumTrainingDraws,combinationsPerDraw,trainingEndBeforeEveryTarget:targets.every((target)=>target.trainingEndDate<target.drawDate),strategy,baseline,upliftVsRandom:baseline.averageMainHits?(strategy.averageMainHits-baseline.averageMainHits)/baseline.averageMainHits:0,targets,executionMs:Math.round(performance.now()-started)};
}
