import type { GeneratedCombination,GeneratorConstraints,GenerationMethod } from "@/features/generator/types";

export class GeneratorConstraintError extends Error{constructor(message:string){super(message);this.name="GeneratorConstraintError";}}
function hashSeed(seed:string){let hash=2166136261;for(let index=0;index<seed.length;index++){hash^=seed.charCodeAt(index);hash=Math.imul(hash,16777619);}return hash>>>0;}
export function createSeededRandom(seed:string){let state=hashSeed(seed);return()=>{state+=0x6d2b79f5;let value=state;value=Math.imul(value^(value>>>15),value|1);value^=value+Math.imul(value^(value>>>7),value|61);return((value^(value>>>14))>>>0)/4294967296;};}
function validateFeasibility(constraints:GeneratorConstraints,previous:number[]){const blocked=new Set(constraints.excluded);if(constraints.excludePreviousDraw)previous.forEach((number)=>blocked.add(number));const available=Array.from({length:49},(_,index)=>index+1).filter((number)=>!blocked.has(number)||constraints.required.includes(number));if(available.length<6)throw new GeneratorConstraintError("Not enough available numbers after exclusions.");const requiredOdd=constraints.required.filter((number)=>number%2===1).length,requiredLow=constraints.required.filter((number)=>number<=24).length;if(constraints.oddCount!==undefined&&(requiredOdd>constraints.oddCount||constraints.required.length-requiredOdd>6-constraints.oddCount))throw new GeneratorConstraintError("Required numbers cannot satisfy the odd/even target.");if(constraints.lowCount!==undefined&&(requiredLow>constraints.lowCount||constraints.required.length-requiredLow>6-constraints.lowCount))throw new GeneratorConstraintError("Required numbers cannot satisfy the low/high target.");}
function satisfies(numbers:number[],constraints:GeneratorConstraints){const sum=numbers.reduce((a,b)=>a+b,0);if(constraints.oddCount!==undefined&&numbers.filter((number)=>number%2===1).length!==constraints.oddCount)return false;if(constraints.lowCount!==undefined&&numbers.filter((number)=>number<=24).length!==constraints.lowCount)return false;if(constraints.minSum!==undefined&&sum<constraints.minSum)return false;if(constraints.maxSum!==undefined&&sum>constraints.maxSum)return false;if(!constraints.allowConsecutive&&numbers.some((number,index)=>index>0&&number-numbers[index-1]===1))return false;if(constraints.maxSameEndingDigit!==undefined){const endings=new Map<number,number>();for(const number of numbers){const ending=number%10;endings.set(ending,(endings.get(ending)??0)+1);}if(Math.max(...endings.values())>constraints.maxSameEndingDigit)return false;}return true;}
function weightedPick(pool:number[],weights:number[],random:()=>number){const total=weights.reduce((a,b)=>a+b,0);let target=random()*total;for(let index=0;index<pool.length;index++){target-=weights[index];if(target<=0)return index;}return pool.length-1;}
function candidate(method:GenerationMethod,constraints:GeneratorConstraints,previous:number[],frequencies:number[],random:()=>number){const blocked=new Set(constraints.excluded);if(constraints.excludePreviousDraw)previous.forEach((number)=>blocked.add(number));const chosen=[...constraints.required];const pool=Array.from({length:49},(_,index)=>index+1).filter((number)=>!blocked.has(number)&&!chosen.includes(number));while(chosen.length<6){const weights=pool.map((number)=>method==="historical_weighted"?(frequencies[number]??0)+1:1);const index=weightedPick(pool,weights,random);chosen.push(pool[index]);pool.splice(index,1);}return chosen.sort((a,b)=>a-b);}
function explanation(method:GenerationMethod,constraints:GeneratorConstraints){const lines=[method==="historical_weighted"?"按 verified 歷史出現次數加一平滑後加權抽樣。":"每個可用號碼使用均勻隨機抽樣。","使用固定 seed，可用相同參數重現結果。"];if(constraints.required.length)lines.push(`固定號碼：${constraints.required.join(", ")}`);if(constraints.excluded.length)lines.push(`排除號碼：${constraints.excluded.join(", ")}`);if(constraints.excludePreviousDraw)lines.push("已排除上一期主號碼。");return lines;}
export function generateCombinations({method,count,seed,constraints,previousDraw=[],frequencies=Array(50).fill(0)}:{method:GenerationMethod;count:number;seed:string;constraints:GeneratorConstraints;previousDraw?:number[];frequencies?:number[]}){validateFeasibility(constraints,previousDraw);const random=createSeededRandom(seed),results:GeneratedCombination[]=[],seen=new Set<string>();let attempts=0;while(results.length<count&&attempts<50000){attempts++;const numbers=candidate(method,constraints,previousDraw,frequencies,random);const key=numbers.join("-");if(seen.has(key)||!satisfies(numbers,constraints))continue;seen.add(key);const score=method==="historical_weighted"?numbers.reduce((sum,number)=>sum+(frequencies[number]??0),0)/6:null;results.push({numbers,historicalScore:score,explanation:explanation(method,constraints)});}if(results.length<count)throw new GeneratorConstraintError(`Constraints are too strict; generated ${results.length} of ${count} combinations after ${attempts} attempts.`);return{combinations:results,attempts};}
