import {describe,expect,it}from"vitest";
import {createSeededRandom,generateCombinations,GeneratorConstraintError}from"@/lib/generator/engine";
import type{GeneratorConstraints}from"@/features/generator/types";
const defaults:GeneratorConstraints={required:[],excluded:[],allowConsecutive:true,excludePreviousDraw:false};
describe("seeded generator",()=>{
  it("replays the same random sequence for the same seed",()=>{const first=createSeededRandom("repeatable"),second=createSeededRandom("repeatable");expect(Array.from({length:20},first)).toEqual(Array.from({length:20},second));});
  it("generates unique sorted valid combinations",()=>{const result=generateCombinations({method:"uniform_random",count:50,seed:"validity",constraints:defaults});expect(new Set(result.combinations.map((item)=>item.numbers.join("-"))).size).toBe(50);for(const item of result.combinations){expect(item.numbers).toHaveLength(6);expect(new Set(item.numbers).size).toBe(6);expect(item.numbers).toEqual([...item.numbers].sort((a,b)=>a-b));expect(item.numbers.every((number)=>number>=1&&number<=49)).toBe(true);}});
  it("honours required, excluded, parity, low, sum, consecutive, and ending constraints",()=>{const constraints:GeneratorConstraints={required:[3],excluded:[1,2,49],oddCount:3,lowCount:3,minSum:100,maxSum:200,allowConsecutive:false,maxSameEndingDigit:1,excludePreviousDraw:true};const result=generateCombinations({method:"conditional_random",count:10,seed:"constraints",constraints,previousDraw:[5,6,7,8,9,10]});for(const{numbers}of result.combinations){expect(numbers).toContain(3);expect(numbers.some((number)=>[1,2,5,6,7,8,9,10,49].includes(number))).toBe(false);expect(numbers.filter((number)=>number%2).length).toBe(3);expect(numbers.filter((number)=>number<=24).length).toBe(3);expect(numbers.reduce((a,b)=>a+b,0)).toBeGreaterThanOrEqual(100);expect(numbers.reduce((a,b)=>a+b,0)).toBeLessThanOrEqual(200);expect(numbers.some((number,index)=>index>0&&number-numbers[index-1]===1)).toBe(false);expect(new Set(numbers.map((number)=>number%10)).size).toBe(6);}});
  it("changes weighted selection deterministically with frequencies",()=>{const frequencies=Array(50).fill(0);frequencies[49]=100000;const result=generateCombinations({method:"historical_weighted",count:5,seed:"weighted",constraints:defaults,frequencies});expect(result.combinations.every((item)=>item.numbers.includes(49))).toBe(true);expect(result.combinations[0].historicalScore).not.toBeNull();});
  it("fails boundedly when constraints are impossible",()=>{expect(()=>generateCombinations({method:"conditional_random",count:2,seed:"impossible",constraints:{...defaults,required:[1,3,5,7,9,11],oddCount:0}})).toThrow(GeneratorConstraintError);});
});
