"use client";
import{AlertTriangle,CheckCircle2,Loader2,RotateCcw,SearchCheck,Trophy}from"lucide-react";
import{useState}from"react";
import{NumberBall}from"@/components/draw/number-ball";
import{formatDrawDate}from"@/components/draw/draw-card";
import type{DrawSummary}from"@/features/draws/types";
type Result={drawNumber:string;drawDate:string;selectedNumbers:number[];mainMatches:number[];extraMatch:number|null;mainHitCount:number;hasExtraHit:boolean;prizeDivision:number|null;prizeLabel:string;dividend:number|null;winningNumbers:number[];extraNumber:number};
const money=new Intl.NumberFormat("zh-HK",{style:"currency",currency:"HKD",maximumFractionDigits:0});
export function CheckerWorkbench({draws,locale,initialNumbers=[]}:{draws:DrawSummary[];locale:string;initialNumbers?:number[]}){const[drawNumber,setDrawNumber]=useState(draws[0]?.drawNumber??""),[selected,setSelected]=useState<number[]>(initialNumbers),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  function toggle(number:number){setResult(null);setError(null);setSelected((current)=>current.includes(number)?current.filter((item)=>item!==number):current.length<6?[...current,number].sort((a,b)=>a-b):current);}
  function clear(){setSelected([]);setResult(null);setError(null);}
  async function check(){if(selected.length!==6){setError("請選擇剛好六個不同號碼。");return;}setBusy(true);setError(null);try{const response=await fetch("/api/checker",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({drawNumber,numbers:selected})});const payload=await response.json()as{data?:Result;error?:{message:string}};if(!response.ok||!payload.data)throw new Error(payload.error?.message??"核對失敗");setResult(payload.data);}catch(caught){setError(caught instanceof Error?caught.message:"核對失敗");}finally{setBusy(false);}}
  return <div className="mt-9 grid gap-6 xl:grid-cols-[1fr_.9fr]"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><label><span className="mb-2 block text-sm text-slate-400">開獎期數</span><input list="verified-draws" value={drawNumber} onChange={(event)=>{setDrawNumber(event.target.value);setResult(null);}} className="min-h-11 w-full rounded-xl border border-white/12 bg-slate-950/50 px-3 outline-none focus:border-indigo-400" placeholder="輸入或選擇期數"/><datalist id="verified-draws">{draws.map((draw)=><option key={draw.drawNumber} value={draw.drawNumber}>{formatDrawDate(draw.drawDate,locale)}</option>)}</datalist></label><div className="mt-6 flex items-center justify-between"><div><h2 className="font-bold">選擇六個號碼</h2><p className="mt-1 text-sm text-slate-400">已選 {selected.length} / 6</p></div><button type="button" onClick={clear} className="flex min-h-10 items-center gap-2 rounded-xl border border-white/12 px-3 text-sm"><RotateCcw className="size-4"/>清除</button></div><div className="mt-4 grid grid-cols-7 gap-2">{Array.from({length:49},(_,index)=>index+1).map((number)=>{const active=selected.includes(number);return <button key={number} type="button" aria-pressed={active} aria-label={`號碼 ${number}`} onClick={()=>toggle(number)} className={`aspect-square rounded-full border font-mono text-sm font-bold transition ${active?"border-indigo-300 bg-indigo-500 text-white shadow-lg shadow-indigo-500/20":"border-white/10 bg-slate-950/35 text-slate-300 hover:border-indigo-400/50"}`}>{number}</button>;})}</div><button type="button" disabled={busy||selected.length!==6||!drawNumber} onClick={()=>void check()} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-500 px-5 font-bold hover:bg-indigo-400 disabled:opacity-40">{busy?<Loader2 className="size-5 animate-spin"/>:<SearchCheck className="size-5"/>}{busy?"核對中…":"核對結果"}</button>{error&&<p role="alert" className="mt-4 rounded-xl border border-red-400/20 bg-red-400/8 p-4 text-sm text-red-200"><AlertTriangle className="mr-2 inline size-4"/>{error}</p>}</section>
    <section className="rounded-2xl border border-white/10 bg-[#141b2d]/80 p-5">{result?<ResultPanel result={result} locale={locale}/>:<div className="grid min-h-100 place-items-center text-center"><div><SearchCheck className="mx-auto size-10 text-slate-600"/><h2 className="mt-4 text-xl font-bold">等待核對</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-400">選擇六個號碼及一個 verified 開獎期數，系統會標示主號碼、特別號碼及獎項。</p></div></div>}</section></div>;
}
function ResultPanel({result,locale}:{result:Result;locale:string}){const mainMatches=new Set(result.mainMatches);return <div><div className={`rounded-2xl border p-5 text-center ${result.prizeDivision?"border-emerald-400/25 bg-emerald-400/8":"border-white/10 bg-white/[.025]"}`}>{result.prizeDivision?<Trophy className="mx-auto size-9 text-amber-300"/>:<CheckCircle2 className="mx-auto size-9 text-slate-500"/>}<p className="mt-3 text-sm text-slate-400">核對結果</p><h2 className="mt-1 text-3xl font-bold">{result.prizeLabel}</h2><p className="mt-2 text-sm">命中 {result.mainHitCount} 個主號碼{result.hasExtraHit?"及特別號碼":""}</p>{result.dividend!==null&&<p className="mt-2 font-semibold text-emerald-300">參考派彩：{money.format(result.dividend)}</p>}</div><div className="mt-6"><p className="text-sm text-slate-400">第 {result.drawNumber} 期 · {formatDrawDate(result.drawDate,locale)}</p><h3 className="mt-4 font-bold">開獎號碼</h3><div className="mt-3 flex flex-wrap gap-2">{result.winningNumbers.map((number)=><NumberBall key={number} number={number}/>)}<span className="self-center text-slate-500">+</span><NumberBall number={result.extraNumber} extra/></div><h3 className="mt-6 font-bold">你的號碼</h3><div className="mt-3 flex flex-wrap gap-2">{result.selectedNumbers.map((number)=>{const main=mainMatches.has(number),extra=result.extraMatch===number;return <span key={number} className={`grid size-12 place-items-center rounded-full border font-mono font-bold ${main?"border-emerald-300 bg-emerald-500 text-slate-950":extra?"border-amber-300 bg-amber-300 text-slate-950":"border-white/12 bg-slate-950/40 text-slate-400"}`}>{number}</span>;})}</div><div className="mt-5 flex flex-wrap gap-4 text-xs"><span className="flex items-center gap-2"><i className="size-3 rounded-full bg-emerald-500"/>主號碼命中</span><span className="flex items-center gap-2"><i className="size-3 rounded-full bg-amber-300"/>特別號碼命中</span></div></div></div>;}
