import type { AnalyticsDraw, NumberStatistic, PairStatistic, PatternStatistics } from "@/features/analytics/types";

function selectedNumbers(draw: AnalyticsDraw, includeExtra: boolean) { return includeExtra ? [...draw.mainNumbers, draw.extraNumber] : draw.mainNumbers; }
export function calculateNumberFrequency(draws: AnalyticsDraw[], includeExtra = false) { const counts = Array.from({ length: 50 }, () => 0); for (const draw of draws) for (const number of selectedNumbers(draw, includeExtra)) counts[number]++; return counts; }
export function calculateDrawsSinceLastSeen(draws: AnalyticsDraw[], includeExtra = false) { const result: Array<number | null> = Array.from({ length: 50 }, () => null); const descending = [...draws].sort((a,b) => b.drawDate.localeCompare(a.drawDate)); for (let index=0; index<descending.length; index++) for (const number of selectedNumbers(descending[index], includeExtra)) if (result[number] === null) result[number] = index; return result; }
export function calculateAverageGap(draws: AnalyticsDraw[], includeExtra = false) { const positions: number[][] = Array.from({ length: 50 }, () => []); [...draws].sort((a,b) => a.drawDate.localeCompare(b.drawDate)).forEach((draw,index) => { for (const number of selectedNumbers(draw, includeExtra)) positions[number].push(index); }); return positions.map((items) => items.length < 2 ? null : items.slice(1).reduce((sum,position,index) => sum + position-items[index],0)/(items.length-1)); }
export function calculateExpectedFrequency(drawCount: number, includeExtra = false) { return drawCount * (includeExtra ? 7 : 6) / 49; }
export function calculateDeviationFromExpected(actual: number, expected: number) { return expected === 0 ? 0 : (actual-expected)/expected; }
export function calculateNumberStatistics(draws: AnalyticsDraw[], includeExtra = false): NumberStatistic[] { const frequencies=calculateNumberFrequency(draws,includeExtra), since=calculateDrawsSinceLastSeen(draws,includeExtra), gaps=calculateAverageGap(draws,includeExtra), expected=calculateExpectedFrequency(draws.length,includeExtra); return Array.from({length:49},(_,index)=>({ number:index+1, frequency:frequencies[index+1], expectedFrequency:expected, deviationFromExpected:calculateDeviationFromExpected(frequencies[index+1],expected), drawsSinceLastSeen:since[index+1], averageGap:gaps[index+1] })); }
export function calculatePatternFeatures(draw: AnalyticsDraw) { const numbers=[...draw.mainNumbers].sort((a,b)=>a-b), odd=numbers.filter((n)=>n%2===1).length, low=numbers.filter((n)=>n<=24).length; return { sum:numbers.reduce((a,b)=>a+b,0), odd, even:6-odd, low, high:6-low, hasConsecutive:numbers.some((number,index)=>index>0 && number-numbers[index-1]===1) }; }
export function calculatePatternStatistics(draws: AnalyticsDraw[]): PatternStatistics { const features=draws.map(calculatePatternFeatures), sums=features.map((item)=>item.sum), patternCount=(selector:(item:ReturnType<typeof calculatePatternFeatures>)=>string)=>Object.entries(features.reduce<Record<string,number>>((acc,item)=>{const key=selector(item);acc[key]=(acc[key]??0)+1;return acc;},{})).map(([key,count])=>({key,count})); const oddEven=patternCount((x)=>`${x.odd}-${x.even}`).map(({key,count})=>{const [odd,even]=key.split("-").map(Number);return {odd,even,count};}).sort((a,b)=>a.odd-b.odd); const lowHigh=patternCount((x)=>`${x.low}-${x.high}`).map(({key,count})=>{const [low,high]=key.split("-").map(Number);return {low,high,count};}).sort((a,b)=>a.low-b.low); const consecutiveDraws=features.filter((x)=>x.hasConsecutive).length; return { drawCount:draws.length, averageSum:draws.length?sums.reduce((a,b)=>a+b,0)/draws.length:0, minimumSum:sums.length?Math.min(...sums):0, maximumSum:sums.length?Math.max(...sums):0, oddEven, lowHigh, consecutiveDraws, consecutiveRate:draws.length?consecutiveDraws/draws.length:0 }; }
export function calculatePairCounts(draws: AnalyticsDraw[]): PairStatistic[] { const counts=new Map<string,number>(); for(const draw of draws){const numbers=[...draw.mainNumbers].sort((a,b)=>a-b);for(let i=0;i<numbers.length;i++)for(let j=i+1;j<numbers.length;j++){const key=`${numbers[i]}-${numbers[j]}`;counts.set(key,(counts.get(key)??0)+1);}} return [...counts.entries()].map(([key,count])=>({numbers:key.split("-").map(Number) as [number,number],count,rate:draws.length?count/draws.length:0})).sort((a,b)=>b.count-a.count||a.numbers[0]-b.numbers[0]||a.numbers[1]-b.numbers[1]); }
